### ISSUE TITLE
CEDAR: Contributor roles in template

### ISSUE THREAD

**Issue by eslao** [LD4P/requirements#162] opened 2018-07-28 12:30 UTC
Work--Contributor role could link to the RDA relationship designator list.

**Comment by NancyL** [comment] 2018-07-29 21:29
Problem is with relationships in RDA is that as linked data they are properties, not classes. There is no online, usable list of RDA relationship designators that are simply terms. Strangely, the same problem exists with the MARC relators--if you look at the skos, they are actually properties and not classes, and so can't be loaded into BioPortal.

**Comment by graybeal** [comment] 2018-07-31 23:27
Properties can be loaded into BioPortal, and can be selected in the property relations in CEDAR. (I think this was not true when Nancy started creating these templates.) So tentatively this could be fixed in the template, but I won't be sure of that until Nancy tells me it's true. :-)

**Comment by NancyL** [comment] 2018-08-01 21:36
The problem is that while they are published as properties, the BIBFRAME relators are classes. I don't think you can look up a property and use as a class in BioPortal (not necessarily a bug!)

**Comment by michelleif** [comment] 2020-04-01 22:59
@NancyL @eslao I'm reviewing these old requirements against Sinopia's current features (even though this was a comment about CEDAR)
it looks like Sinopia is able to offer Relationship Designator as a lookup

does Sinopia have the problem explained in this issue?

**Closed as completed** 2020-04-29 19:13 UTC
Labels: CEDAR
